//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmigrationApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employment
    {
        public int EmploymentID { get; set; }
        public string EmployerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Zipcode { get; set; }
        public string JobTitle { get; set; }
        public string Salary { get; set; }
        public System.DateTime DateStarted { get; set; }
        public System.DateTime DateLeft { get; set; }
        public string Client { get; set; }
        public string JobDescription { get; set; }
        public int PersonID { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
