//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmigrationApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormerSpouse
    {
        public int FormerSpouseID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public System.DateTime DateofMarriage { get; set; }
        public string CityofMarriage { get; set; }
        public string CountryofMarriage { get; set; }
        public string CityofDivorced { get; set; }
        public string CountryofDivorced { get; set; }
        public System.DateTime DateofDiverse { get; set; }
        public System.DateTime DateofDeath { get; set; }
        public int PersonID { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
