//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmigrationApplication.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class immigrationEntities : DbContext
    {
        public immigrationEntities()
            : base("name=immigrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Employment> Employments { get; set; }
        public virtual DbSet<FormerSpouse> FormerSpouses { get; set; }
        public virtual DbSet<LastArrivalDetail> LastArrivalDetails { get; set; }
        public virtual DbSet<OtherDetail> OtherDetails { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PreviousApplication> PreviousApplications { get; set; }
        public virtual DbSet<USRelative> USRelatives { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
    
        public virtual ObjectResult<sp_PrintDetails_Result> PrintDetails(Nullable<int> personID)
        {
            var personIDParameter = personID.HasValue ?
                new ObjectParameter("PersonID", personID) :
                new ObjectParameter("PersonID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PrintDetails_Result>("PrintDetails", personIDParameter);
        }
    
        public virtual ObjectResult<sp_PrintDetails_Result> sp_PrintDetailsByID(Nullable<int> personID)
        {
            var personIDParameter = personID.HasValue ?
                new ObjectParameter("PersonID", personID) :
                new ObjectParameter("PersonID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PrintDetails_Result>("sp_PrintDetailsByID", personIDParameter);
        }
    
        public virtual ObjectResult<sp_personjoin_Result> sp_personjoin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_personjoin_Result>("sp_personjoin");
        }
    }
}
