//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmigrationApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastArrivalDetail
    {
        public int LastArrivalDetailsID { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public System.DateTime DateofArrival { get; set; }
        public string NameofFlight { get; set; }
        public string FlightNumber { get; set; }
        public string AppliedPermanentResident { get; set; }
        public string RefusedVisa { get; set; }
        public string USConsulate { get; set; }
        public int PersonID { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
