//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmigrationApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviousApplication
    {
        public int PreviousApplicationID { get; set; }
        public string ApplicationType { get; set; }
        public System.DateTime DateApplied { get; set; }
        public string StatusGranted { get; set; }
        public string IndicateIfDenied { get; set; }
        public string CapGap { get; set; }
        public int PersonID { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
